name: Test, Build, and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests
        run: |
          npm run test  # Adjust the command based on your testing setup

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install

      - name: Build React App
        run: |
          npm run build

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/build
    needs: build
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3 Bucket
        run: |
          aws s3 sync build/ s3://region4casestudy
